version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-cache-{{ checksum "go.sum"  }}
      - run:
          name: "Go: Download"
          command: go mod download
      - save_cache:
          key: go-cache-{{ checksum "go.sum"  }}
          paths:
            - /usr/local/go
      - run:
          name: "Go: Test"
          command: |
            go test -v ./...
      - run:
          name: "Go: Build"
          command: go build

workflows:
  test:
    jobs:
      - test
